import 'dart:typed_data';

import 'package:flutter_test/flutter_test.dart';
import 'package:mocktail/mocktail.dart';
import 'package:stayon/core/models/attachment.dart';
import 'package:stayon/core/models/extraction_result.dart';
import 'package:stayon/core/models/item.dart';
import 'package:stayon/core/models/item_status.dart';
import 'package:stayon/features/attachments/data/attachment_repository.dart';
import 'package:stayon/core/models/item_category.dart';
import 'package:stayon/core/models/item_date_type.dart';

class _FakeAttachment extends Fake implements Attachment {}

Item _stubItem({
  String id = 'item-123',
  String name = 'Test Item',
  String ownerId = 'user-456',
}) => Item(
  id: id,
  ownerId: ownerId,
  name: name,
  category: ItemCategory.grocery,
  dateType: ItemDateType.expires,
  targetDate: DateTime.utc(2026, 12, 31),
  currencyCode: 'PHP',
  status: ItemStatus.active,
  createdAt: DateTime.utc(2026, 5, 24),
  updatedAt: DateTime.utc(2026, 5, 24),
);


ExtractionResult _barcodeResult({
  String productName = 'Heinz Ketchup',
  String brands = 'Heinz',
  String expirationDate = '2026-12-31',
  double confidence = 0.95,
}) => ExtractionResult(
  type: 'barcode',
  data: {
    'code': '8718507330427',
    'product_name': productName,
    'brands': brands,
    'expiration_date': expirationDate,
  },
  confidence: confidence,
);

void main() {
  setUpAll(() {
    registerFallbackValue(_FakeAttachment());
    registerFallbackValue(Uint8List(0));
  });

  group('Barcode Attachment Save Flow - Unit Tests', () {
    test(
      'should have correct attachment model for barcode',
      () {
        final item = _stubItem();
        final barcodeResult = _barcodeResult();
        final barcodeCode = barcodeResult.data['code'] as String;

        final attachment = Attachment(
          id: '', // Will be generated by repository
          ownerId: item.ownerId,
          itemId: item.id,
          filename: 'barcode_$barcodeCode.json',
          contentType: 'application/json',
          fileSizeBytes: 200,
          storagePath: 'local://barcode_$barcodeCode',
          storageTier: 'local',
          extractionType: 'barcode',
          extractionData: barcodeResult.data,
          extractionConfidence: barcodeResult.confidence,
          extractionReviewedAt: DateTime.now(),
          createdAt: DateTime.now(),
          updatedAt: DateTime.now(),
        );

        expect(attachment.extractionType, 'barcode');
        expect(attachment.itemId, item.id);
        expect(attachment.extractionData?['product_name'], 'Heinz Ketchup');
        expect(attachment.extractionConfidence, 0.95);
        expect(attachment.storagePath, 'local://barcode_8718507330427');
        expect(attachment.fileSizeBytes, 200);
      },
    );

    test(
      'should create attachment with empty bytes (barcode is metadata-only)',
      () {
        final emptyBytes = Uint8List(0);
        expect(emptyBytes.isEmpty, true);
        expect(emptyBytes.lengthInBytes, 0);
      },
    );

    test(
      'should have minimal file size for barcode metadata',
      () {
        const barcodeMetadataSize = 200; // ~200 bytes typical
        expect(barcodeMetadataSize, lessThanOrEqualTo(500));
      },
    );

    test(
      'QuotaException should be thrown for attachment limit',
      () {
        final exception = QuotaException(
          'attachment_limit_exceeded',
          'Free tier limited to 10 attachments per item',
        );

        expect(exception.code, 'attachment_limit_exceeded');
        expect(
          exception.message,
          contains('Free tier limited to 10 attachments'),
        );
      },
    );

    test(
      'QuotaException should be thrown for storage limit',
      () {
        final exception = QuotaException(
          'storage_limit_exceeded',
          'Free tier limited to 50 MB total storage',
        );

        expect(exception.code, 'storage_limit_exceeded');
        expect(exception.message, contains('50 MB'));
      },
    );

    test(
      'AttachmentException should be thrown for RLS violations',
      () {
        final exception = AttachmentException(
          'rls',
          'You do not have access to this attachment',
        );

        expect(exception.code, 'rls');
        expect(exception.message, contains('do not have access'));
      },
    );

    test(
      'extraction data should contain all barcode fields',
      () {
        final barcodeResult = _barcodeResult(
          productName: 'Coca Cola 500ml',
          brands: 'Coca-Cola',
          expirationDate: '2026-08-15',
        );

        expect(barcodeResult.data['code'], '8718507330427');
        expect(barcodeResult.data['product_name'], 'Coca Cola 500ml');
        expect(barcodeResult.data['brands'], 'Coca-Cola');
        expect(barcodeResult.data['expiration_date'], '2026-08-15');
      },
    );

    test(
      'extraction result should have barcode type',
      () {
        final barcodeResult = _barcodeResult();
        expect(barcodeResult.type, 'barcode');
        expect(barcodeResult.confidence, greaterThanOrEqualTo(0.0));
        expect(barcodeResult.confidence, lessThanOrEqualTo(1.0));
      },
    );

    test(
      'attachment should use barcode code in storage path',
      () {
        const barcodeCode = '8718507330427';
        const storagePath = 'local://barcode_$barcodeCode';

        expect(storagePath, startsWith('local://barcode_'));
        expect(storagePath, contains(barcodeCode));
      },
    );

    test(
      'attachment filename should use barcode code',
      () {
        const barcodeCode = '8718507330427';
        const filename = 'barcode_$barcodeCode.json';

        expect(filename, startsWith('barcode_'));
        expect(filename, endsWith('.json'));
        expect(filename, contains(barcodeCode));
      },
    );
  });
}
